apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harus-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/azusachino/harus-charts
    targetRevision: HEAD
    path: kubernetes/manifests
  destination:
    name: okj-exchange-test
    namespace: default
